## 1)  Tensor basics

In [1]:
import torch

In [2]:
x=torch.empty(2,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.6165e+17]])


In [3]:
x=torch.rand(2,3)
print(x)

tensor([[0.2852, 0.6966, 0.9906],
        [0.7995, 0.7936, 0.8189]])


In [4]:
x=torch.zeros(2,5, dtype=torch.int) # or ones
print(x.dtype)
print(x.size())

torch.int32
torch.Size([2, 5])


In [5]:
x=torch.tensor([2.05,3.6])
print(x)

tensor([2.0500, 3.6000])


In [6]:
x=torch.rand(2,2)
y=torch.rand(2,2)
# z=torch.add(x,y) , torch.add, torch.div , torch.mul
print(x+y)
z=torch.zeros(2,2)
print(z.add_(x))
print(x)

tensor([[1.3834, 1.4277],
        [0.3161, 0.7511]])
tensor([[0.4407, 0.8174],
        [0.1239, 0.5234]])
tensor([[0.4407, 0.8174],
        [0.1239, 0.5234]])


In [7]:
x=torch.rand(5,3)
print(x)
print(x[:,0])
print(x[1,1])
print(x[1,1].item())

tensor([[0.5527, 0.6730, 0.0570],
        [0.6424, 0.5401, 0.1469],
        [0.8722, 0.1294, 0.0989],
        [0.1093, 0.1162, 0.5466],
        [0.7530, 0.0806, 0.6525]])
tensor([0.5527, 0.6424, 0.8722, 0.1093, 0.7530])
tensor(0.5401)
0.5401225686073303


In [8]:
x=torch.rand(4,4)
print(x)
y=x.view(16)
print(y)
z=x.view(-1,8)
print(z)

tensor([[0.8517, 0.5722, 0.1721, 0.0258],
        [0.9866, 0.2218, 0.7271, 0.9021],
        [0.3097, 0.0515, 0.1788, 0.0327],
        [0.6627, 0.3885, 0.4106, 0.6747]])
tensor([0.8517, 0.5722, 0.1721, 0.0258, 0.9866, 0.2218, 0.7271, 0.9021, 0.3097,
        0.0515, 0.1788, 0.0327, 0.6627, 0.3885, 0.4106, 0.6747])
tensor([[0.8517, 0.5722, 0.1721, 0.0258, 0.9866, 0.2218, 0.7271, 0.9021],
        [0.3097, 0.0515, 0.1788, 0.0327, 0.6627, 0.3885, 0.4106, 0.6747]])


In [9]:
import numpy as np

In [10]:
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [11]:
a=np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [12]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    x=torch.ones(5,device=device)
    y=torch.ones(5)
    y=y.to(device)
    z=x+y
    z=z.to("cpu")

In [13]:
x=torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


## 2) Gradient calculation

In [14]:
x=torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.1435, -1.3059,  0.1259], requires_grad=True)


In [15]:
y=x+2
print(y)

tensor([2.1435, 0.6941, 2.1259], grad_fn=<AddBackward0>)


In [16]:
z=y*y*2
print(z)

tensor([9.1889, 0.9637, 9.0389], grad_fn=<MulBackward0>)


In [17]:
z=z.mean()
print(z)

tensor(6.3971, grad_fn=<MeanBackward0>)


In [18]:
z.backward() #dz/dx
print(x.grad)

tensor([2.8579, 0.9255, 2.8345])


In [19]:
z=2*y*y
v=torch.tensor([0.1,1.0,0.001], dtype=torch.float32)
z.backward(v)

In [20]:
x=torch.randn(3, requires_grad=True)
print(x)
x.requires_grad_(False)
print(x)
y=x.detach()
print(y)
with torch.no_grad():
    y=x+2
    print(y)

tensor([ 1.0216,  0.0390, -0.3584], requires_grad=True)
tensor([ 1.0216,  0.0390, -0.3584])
tensor([ 1.0216,  0.0390, -0.3584])
tensor([3.0216, 2.0390, 1.6416])


In [21]:
weights=torch.ones(4,requires_grad=True)

for epoch in range(3):
    model_output=(weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


## 3) Backpropagation

a) forward pass
b) local gradient
c) backward gradient

In [22]:
x=torch.tensor(1.0)
y=torch.tensor(2.0)

w=torch.tensor(1.0, requires_grad=True)

# forward pass and compute the loss
y_hat=w*x
loss=(y_hat-y)**2

print(loss)

# backward pass
loss.backward()
print(w.grad)

# update weights

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


## 4) Gradient descent with autograd and backpropagation

In [23]:
X=np.array([1,2,3,4], dtype=np.float32)
Y=np.array([2,4,6,8], dtype=np.float32)
print(Y)

[2. 4. 6. 8.]


In [24]:
w=0.0

# model prediction

def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y)**2).mean()



In [25]:
# gradient
# J = MSE = 1/N * (w*x - y)**2
# dJ/dw = 1/N * 2x(w*x - y)
def gradient(x, y, y_pred):
    return np.dot(2*x, y_pred - y).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000


In [26]:
# Training

learning_rate=0.01
n_iters=20

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)
    
    # calculate gradients
    dw = gradient(X, Y, y_pred)

    # update weights
    w -= learning_rate * dw

    if epoch % 2 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')
     
print(f'Prediction after training: f(5) = {forward(5):.3f}')

epoch 1: w = 1.200, loss = 30.00000000
epoch 3: w = 1.872, loss = 0.76800019
epoch 5: w = 1.980, loss = 0.01966083
epoch 7: w = 1.997, loss = 0.00050332
epoch 9: w = 1.999, loss = 0.00001288
epoch 11: w = 2.000, loss = 0.00000033
epoch 13: w = 2.000, loss = 0.00000001
epoch 15: w = 2.000, loss = 0.00000000
epoch 17: w = 2.000, loss = 0.00000000
epoch 19: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


In [27]:
X=torch.tensor([1,2,3,4], dtype=torch.float32)
Y=torch.tensor([2,4,6,8], dtype=torch.float32)
print(Y)

w=torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

# model prediction

def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')


# Training
learning_rate=0.01
n_iters=100

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)
    
    # calculate gradients=backward pass
    l.backward() # dw/dl

    # update weights
    with torch.no_grad():
        w -= learning_rate * w.grad
        
    # zero gradient
    w.grad.zero_()

    if epoch % 10 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')
     
print(f'Prediction after training: f(5) = {forward(5):.3f}')

tensor([2., 4., 6., 8.])
Prediction before training: f(5) = 0.000
epoch 1: w = 0.300, loss = 30.00000000
epoch 11: w = 1.665, loss = 1.16278565
epoch 21: w = 1.934, loss = 0.04506890
epoch 31: w = 1.987, loss = 0.00174685
epoch 41: w = 1.997, loss = 0.00006770
epoch 51: w = 1.999, loss = 0.00000262
epoch 61: w = 2.000, loss = 0.00000010
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


## 5) Training pipeline: model, loss & optimizer

1) design model (input, output_size , forward pass)
2) construct loss & optimizer
3) training loop
-forward pass: compute prdictions
-backward pass: gradient
-update weights

In [28]:
import torch
import torch.nn as nn


X=torch.tensor([1,2,3,4], dtype=torch.float32)
Y=torch.tensor([2,4,6,8], dtype=torch.float32)
print(Y)

w=torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

# model prediction

def forward(x):
    return w * x


print(f'Prediction before training: f(5) = {forward(5):.3f}')


# Training
learning_rate=0.01
n_iters=100

loss=nn.MSELoss()
optimizer=torch.optim.SGD([w], lr=learning_rate)

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)
    
    # calculate gradients=backward pass
    l.backward() # dw/dl

    # update weights
    optimizer.step()
    
    # zero gradient
    optimizer.zero_grad()

    if epoch % 10 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')
     
print(f'Prediction after training: f(5) = {forward(5):.3f}')

tensor([2., 4., 6., 8.])
Prediction before training: f(5) = 0.000
epoch 1: w = 0.300, loss = 30.00000000
epoch 11: w = 1.665, loss = 1.16278565
epoch 21: w = 1.934, loss = 0.04506890
epoch 31: w = 1.987, loss = 0.00174685
epoch 41: w = 1.997, loss = 0.00006770
epoch 51: w = 1.999, loss = 0.00000262
epoch 61: w = 2.000, loss = 0.00000010
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


In [29]:
import torch
import torch.nn as nn


X=torch.tensor([[1],[2],[3],[4]], dtype=torch.float32)
Y=torch.tensor([[2],[4],[6],[8]], dtype=torch.float32)

X_test=torch.tensor([5], dtype=torch.float32)


n_samples, n_features=X.shape
print(n_samples, n_features)

input_size=n_features
output_size=n_features

model=nn.Linear(input_size, output_size)

"""
class LinearRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegression, self).__init__()
        # define diferent layers
        self.lin = nn.Linear(input_dim, output_dim)
    def forward(self, x):
        return self.lin(x)
    
model = LinearRegression(input_size, output_size)
"""


print(f'Prediction before training: f(5) = {model(X_test).item():.3f}')


# Training
learning_rate=0.01
n_iters=100

loss=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = model(X)

    # loss
    l = loss(Y, y_pred)
    
    # calculate gradients=backward pass
    l.backward() # dw/dl

    # update weights
    optimizer.step()
    
    # zero gradient
    optimizer.zero_grad()

    if epoch % 10 == 0:
        [w,b]=model.parameters()
        print(f'epoch {epoch+1}: w = {w[0][0]:.3f}, loss = {l:.8f}')
     
print(f'Prediction after training: f(5) = {model(X_test).item():.3f}')

4 1
Prediction before training: f(5) = 1.867
epoch 1: w = 0.820, loss = 23.09988403
epoch 11: w = 1.916, loss = 0.62052631
epoch 21: w = 2.090, loss = 0.03759995
epoch 31: w = 2.114, loss = 0.02126408
epoch 41: w = 2.115, loss = 0.01966038
epoch 51: w = 2.113, loss = 0.01850656
epoch 61: w = 2.110, loss = 0.01742913
epoch 71: w = 2.106, loss = 0.01641469
epoch 81: w = 2.103, loss = 0.01545924
epoch 91: w = 2.100, loss = 0.01455944
Prediction after training: f(5) = 10.201
